apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sampleAPI
  description: The Petstore API
spec:
  type: openapi
  lifecycle: production
  owner: petstore@example.com
  definition:
    $openapi: https://github.com/RapidX-Developer-Studio/withAPI/blob/master/api.yaml
